config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'

  resources :topics, only: [:show, :new, :create] do
    resources :messages, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :creator, class_name: "User", foreign_key: "user_id"
    belongs_to :topic
    
    after_save :broadcast_message
    after_destroy :remove_message

    private

    def broadcast_message
      ActionCable.server.broadcast("message_channel", {method: "add", message_id: self.id.to_s, text: self.content, user_email: self.creator.email, topic_id:  self.topic.id.to_s, creator_id: self.creator.id })
    end

    def remove_message
        ActionCable.server.broadcast("message_channel", {method: "remove", message_id: self.id.to_s, topic_id:  self.topic.id.to_s})
    end
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_and_belongs_to_many :admins, class_name: 'User', join_table: 'admins_topics', associated_foreign_key: 'user_id'
  has_and_belongs_to_many :subscribers, class_name: 'User', join_table: 'subscriber_topics', associated_foreign_key: 'user_id'
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_topics, class_name: 'Topic', foreign_key: 'user_id'
  has_and_belongs_to_many :administered_topics, class_name: 'Topic', join_table: 'admins_topics', associated_foreign_key: 'topic_id'
  has_and_belongs_to_many :subscribed_topics, class_name: 'Topic', join_table: 'subscriber_topics', associated_foreign_key: 'topic_id'
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @topics = Topic.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!
  
    def create
      @topic = Topic.find(params[:topic_id])
      @message = @topic.messages.new(message_params)
      @message.creator = current_user
  
      if @message.save
        redirect_to topic_path(@topic), notice: 'Message created successfully.'
      else
        redirect_to topic_path(@topic), alert: 'Failed to create message.'
      end
    end
  
    def destroy
      @message = Message.find(params[:id])
      @message.destroy
  
      redirect_to topic_path(@message.topic), notice: 'Message deleted successfully.'
    end
  
    private
  
    def message_params
      params.require(:message).permit(:content, :user_id)
    end
  end
  

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    before_action :authenticate_user!

    def show
        @topic = Topic.eager_load(:messages, :subscribers, :admins).find(params[:id])
    end
  
    def new
      @topic = Topic.new
    end

    def create
      @topic = Topic.new(topic_params)
  
      if @topic.save
        redirect_to @topic, notice: 'Topic was successfully created.'
      else
        render :new
      end
    end
  
    private

    def topic_params
      params.require(:topic).permit(:title, :description, :user_id)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/homes/index.html.erb
<h1>Welcome to ActionCable Portfolio Project</h1>
<% if user_signed_in? %>
  <%= link_to "Logout", destroy_user_session_path,  data: { "turbo-method": :delete } %>
  <h2>Topics</h2>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Creator</th>
      </tr>
    </thead>
    <tbody>
      <% @topics.each do |topic| %>
        <tr>
          <td><%= link_to topic.title, topic_path(topic) %></td>
          <td><%= topic.description %></td>
          <td><%= topic.creator.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InnvolabsActioncableIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
<p><strong>Description:</strong> <%= @topic.description %></p>
<p><strong>Created by:</strong> <%= @topic.creator.email %></p>

<p><strong>Admins:</strong> <button id="toggleAdmins">Admins</button></p>
<ul class="toggle-list admins-list" style="display: none;">
  <% @topic.admins.each do |admin| %>
    <li><%= admin.email %></li>
  <% end %>
</ul>

<p><strong>Subscribers:</strong> <button id="toggleSubscribers">Subscribers</button></p>
<ul class="toggle-list subscribers-list" style="display: none;">
  <% @topic.subscribers.each do |subscriber| %>
    <li><%= subscriber.email %></li>
  <% end %>
</ul>

<p><strong>Messages:</strong></p>
<div id="messagesId"> 
<% @topic.messages.each do |message| %>
  <div class="message" data-message-id="<%= message.id %>">
    <p><strong>From:</strong> <%= message.creator.email %></p>
    <p><strong>Content:</strong> <%= message.content %></p>

    <% if current_user == message.creator %>
      <%= link_to "Delete", topic_message_path(@topic, message), data: { "turbo-method": :delete } %>
    <% end %>
  </div>
<% end %>
</div>

<% if current_user.subscribed_topics.include?(@topic) %>
  <div id="message-box">
    <%= form_with(model: [@topic, Message.new], local: true) do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.text_area :content, placeholder: "Type your message here..." %>
      <%= form.submit "Send Message" %>
    <% end %>
  </div>
<% else %>
  <p>You need to be subscribed to this topic to send messages.</p>
<% end %>

<style>
.message {
  border: 1px solid #ccc;
  padding: 10px;
  margin-bottom: 10px;
}

.message p {
  margin: 5px 0;
}

.message a {
  color: blue;
  text-decoration: none;
  margin-right: 10px;
}

.message a:hover {
  text-decoration: underline;
}

.toggle-list {
  list-style-type: none;
  padding: 0;
}

.toggle-list li {
  margin-bottom: 5px;
  font-size: 14px;
}

.toggle-list li:before {
  content: "\2022";
  color: #333; 
  display: inline-block;
  width: 1em;
  margin-left: -1em;
}
</style>


<script>
document.addEventListener('DOMContentLoaded', function() {
  var toggleAdminsButton = document.getElementById('toggleAdmins');
  var toggleSubscribersButton = document.getElementById('toggleSubscribers');

  var adminsList = document.querySelector('.admins-list');
  var subscribersList = document.querySelector('.subscribers-list');

  toggleAdminsButton.addEventListener('click', function() {
    adminsList.style.display = (adminsList.style.display === 'none') ? 'block' : 'none';
  });

  toggleSubscribersButton.addEventListener('click', function() {
    subscribersList.style.display = (subscribersList.style.display === 'none') ? 'block' : 'none';
  });
});
</script>